Contact form added
ehs9nino/portfolio pull request #5
Opened 2022-03-29 19:54 UTC by ehs9nino

2022-03-29 22:13 UTC, ehs9nino commented
In the contact form section, I worked with my coding partner Sameh & we created a UX form in which all the widgets are designed inside the "< UL >" tag. Also, we used the flexbox and we made our UX user-friendly. We integrated & storing our  UX data in the Formspree platform. 
 The template really meets the requirements that are provided in Figma. I would like to see any good suggestions if we have mistakes, please!

2022-03-29 23:28 UTC, nicupop729 requested changes
# STATUS: Required Changes ♻️

Hi @ehs9nino & @sameh080081, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/iZKF7CKpEEva2OZE6a/giphy.gif)

### Required Changes ♻️

- [ ] _Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-29 23:28 UTC, nicupop729 commented on style.css
> +  width: 303px;
Our web page should be responsive to different types and sizes of screen devices.

- [ ] Please remove the fixed width, and set the width as wide as of the inputs; :+1:

2022-03-29 23:28 UTC, nicupop729 commented on style.css
> +}
- [ ] Kindly, try to centre in the middle of the page the form button in order to match the Figma design;
Figma design:
![image](https://user-images.githubusercontent.com/83596135/160721830-7327fa21-c401-4705-90a1-684a5a7dcc8b.png)

Your design:
![image](https://user-images.githubusercontent.com/83596135/160721932-7dfc37c6-1081-4bdd-8f1c-083dc604afa2.png)

2022-03-29 23:28 UTC, nicupop729 commented on style.css
> +}
Button interactions such as hover, active (when it's pressed), disabled and enable (default state) should be styled as shown in the Figma template.
Please implement the missing states for the links/buttons in your app (at least for the pressed state / active state).
Here is a very useful link to study different states for links/buttons: [Styling links](https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Styling_links)

Figma design:
![image](https://user-images.githubusercontent.com/83596135/160722459-30ff915e-8929-4d9d-9ed2-b94a97cac0b8.png)

2022-03-30 05:18 UTC, ehs9nino commented
@nicupop729 thanks for identifying the errors in my mobile- portfolio. 
I tried to fix all the issues according to my understanding of the fixes you recommended, I am sure it will be more helpful if I apply these changes on my desktop versions as well.

2022-03-30 05:28 UTC, Deepakdanger approved these changes
Hi @ehs9nino, 

### Status: Approved ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚢 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-30 05:32 UTC, ehs9nino commented
Thanks, @Deepakdanger for the review!

2022-03-30 05:32 UTC, merged