Main-section desktop design
ehs9nino/portfolio pull request #6
Opened 2022-03-31 04:56 UTC by ehs9nino

Now I want to make the design compatible with my desktop version.

2022-03-31 17:46 UTC, ehs9nino commented
I have tried to make a responsive web design & applied media queries. For 786px or above is showing a desktop compatible version. I try to make it more similar to the design that I am following from Figma.
(link- https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=34%3A1278)

Please let me know If I need any changes making a design similar to that or maybe if even I am not applying any important concepts, thanks!

2022-03-31 18:11 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @ehs9nino👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media3.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-31 18:11 UTC, thecodechaser commented on desktop.css
> +/* stylelint-disable csstree/validator */
- [ ] There is some margin around the page body and a white border appearing and it's not looking good, Please fix this issue to make your project looks more professional.
 - To fix this you can add `margin: 0;` in your body class.

2022-03-31 18:11 UTC, thecodechaser commented on index.html
>            <div class="line"></div>
- [ ] Great job on the design but for this project you are supposed to stick to the [Figma ](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471)design as much as possible. Please reduce the gap between project cards and make sure it matches the design on the template.

### Your design

![image](https://user-images.githubusercontent.com/83803414/161120040-a688fc36-0f9b-430d-bd06-5cc7f48fa24e.png)

### Figma design

![image](https://user-images.githubusercontent.com/83803414/161120083-56a43a03-8c97-4b91-8271-c36603c521b8.png)

2022-03-31 18:11 UTC, thecodechaser commented on index.html
>            <h1>My Recent Works</h1>
- [ ] When we hover on any project the content of the card should be replaced with the `see project` button and the background without gradient. Please fix this issue and make sure it matches the design on the [Figma ](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471)template.

#### See this image of Figma design, The mouse hovers on the first project and we can see it's showing the see project button and the content of the card has been changed. If you still need more clarification please see this [project](https://devmahmoud.github.io/portfolio/).

![image](https://user-images.githubusercontent.com/83803414/161078036-f0f7012f-31ac-4d0c-9142-0d106895cd93.png)

2022-03-31 18:11 UTC, thecodechaser commented on index.html
>          <div class="about-me-btn"><input type="button" class="about-me-button" value="Get my Resume"></div>
- [ ] Please apply the correct padding for this button and make sure it matches the design on the template.

### Your design

![image](https://user-images.githubusercontent.com/83803414/161120940-2d1c84d8-4e48-43cd-a2fa-7b8ab259b650.png)

### Figma design

![image](https://user-images.githubusercontent.com/83803414/161120984-10533d8f-a25d-46ca-9426-e17618b7df00.png)

2022-03-31 18:11 UTC, thecodechaser commented on index.html
> +        <ul class="discussion">
- [ ] Please apply the correct gap between the technologies, each technology should be listed in the same line and make sure it matches the design on the template.

### Your design

![image](https://user-images.githubusercontent.com/83803414/161121236-3edf6424-cad3-4a83-b6fe-77b46a118d3e.png)

### Figma design

![image](https://user-images.githubusercontent.com/83803414/161121281-a01a1912-cbfd-44d5-bf94-473bcfaf936a.png)

2022-03-31 18:11 UTC, thecodechaser commented on index.html
> +      <form class="from1" action="https://formspree.io/f/xdoblzqe" method="post">
- [ ] The form details contain approx 35% of the window width and the form contains the remaining width, Please make sure you follow the width for each section and your design should match the Figma template

### Your design

![image](https://user-images.githubusercontent.com/83803414/161121855-68b6ede4-e223-460c-af82-60b86fa35784.png)

### Figma design

![image](https://user-images.githubusercontent.com/83803414/161121904-83e03dfc-40d6-48b2-9522-32498515005d.png)

2022-04-01 03:19 UTC, ehs9nino commented on index.html
>            <h1>My Recent Works</h1>
@thecodechaser  thanks but here I am facing a problem that all the remaining pictures are coming with the gradients.  I understand the concept but If I know the way how to remove the gradient then I can easily apply the concept.
(https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=34%3A1278)
Please check is there any way I can pick a background picture from Figma without the gradient?

2022-04-01 06:38 UTC, thecodechaser commented on index.html
>            <h1>My Recent Works</h1>
@ehs9nino, Hello You can download the image from below :
 
![Img Placeholder](https://user-images.githubusercontent.com/83803414/161208688-46cb00de-97cd-4397-b489-d50d41df5e91.png)

2022-04-01 06:43 UTC, ehs9nino commented on index.html
>            <h1>My Recent Works</h1>
@thecodechaser  thanks but in that case, I will have only this image to use for all the backgrounds I guess.

2022-04-01 06:44 UTC, thecodechaser commented on index.html
>            <h1>My Recent Works</h1>
@ehs9nino, Yes you can use this image for all the backgrounds

2022-04-01 06:50 UTC, ehs9nino commented on index.html
>            <h1>My Recent Works</h1>
@thecodechaser  okay thanks!

2022-04-01 10:36 UTC, ehs9nino commented on desktop.css
> +/* stylelint-disable csstree/validator */
@thecodechaser I can't understand the behavior or what exactly is happening when I try to inspect. for example, is showing outside from the body container. 

Please let me know if there is a recommendation.

![Screenshot from 2022-04-01 15-31-48](https://user-images.githubusercontent.com/93433477/161247370-a3ec05c9-f32a-43a4-b808-ac78e5eac6d9.png)

2022-04-02 00:51 UTC, ehs9nino commented
@thecodechaser I finalized this task according to the best of my understanding to make this desktop portfolio the best and also I try to stick to the Figma design as well. 
In addition, I did some major changes like I used media queries starting from 1024 pixels ( iPad Landscape & Desktops) instead of 768 pixels ( I iPad & Galaxy Tab). In order to show my content more responsive, I applied media queries additionally to some sections in my HTML document. 
Please guide me if there are any major changes required in this design, thanks!

2022-04-02 01:00 UTC, OLIPLICHE approved these changes
Hi @ehs9nino , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-02 01:09 UTC, merged